query Hikes {
    hikingTrails {
        name
    }
    hikingTrail(key: "ak") {
        name
        key
        stamps {
            name
            description
            pointIdx
            distanceFromNext
        }
        path {
            points {
                lat
                lon
            }
        }
    }
}
