query Hikes {
    hikes {
        name
    }
    hike(key: "ak") {
        name
        key
        stampingLocations {
            name
            description
        }
        path {
            points {
                lat
                lon
            }
        }
    }
}
